import sys
from cognitive_mapping import SkeletonSpec, get_skeleton_spec
from skeleton_generation import generate_shape_skeleton
from shape_generation import generate_mirror_reflection

def test_tree_skeleton():
    print("Testing TreeSkeleton...")
    spec = SkeletonSpec(archetype="tree", voxel_count=10, num_branches=3,
                       direction_spread="moderate", packing="medium")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Tree shape is disconnected! {sfs['number_of_components']}"
        assert sfs["voxel_count"] == 10, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("TreeSkeleton passed constraints.")

def test_tree_sparse_elongated():
    """Tree with sparse packing and elongated 3D spread."""
    print("Testing TreeSkeleton (sparse/elongated_3d)...")
    spec = SkeletonSpec(archetype="tree", voxel_count=10, num_branches=2,
                       direction_spread="elongated_3d", packing="sparse")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Disconnected!"
        assert sfs["voxel_count"] == 10, f"Voxel count mismatch!"
    print("TreeSkeleton (sparse/elongated_3d) passed constraints.")

def test_tree_dense_planar():
    """Tree with dense packing and planar spread."""
    print("Testing TreeSkeleton (dense/planar)...")
    spec = SkeletonSpec(archetype="tree", voxel_count=10, num_branches=5,
                       direction_spread="planar", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Disconnected!"
    print("TreeSkeleton (dense/planar) passed constraints.")

def test_chiral_skeleton():
    print("Testing AsymmetricSkeleton...")
    spec = SkeletonSpec(archetype="chiral", voxel_count=8,
                       direction_spread="moderate", packing="medium", planarity="low")
    success_count = 0
    for i in range(20):
        shape = generate_shape_skeleton(spec)
        mirror = generate_mirror_reflection(shape["voxels"], (7, 7, 7))
        if mirror is not None:
             success_count += 1
    print(f"AsymmetricSkeleton generated {success_count}/20 chiral shapes")
    assert success_count > 15, "Too many achiral shapes generated by AsymmetricSkeleton"
    print("AsymmetricSkeleton passed constraints.")

def test_chiral_elongated():
    """Chiral with elongated 3D direction spread."""
    print("Testing AsymmetricSkeleton (elongated_3d)...")
    spec = SkeletonSpec(archetype="chiral", voxel_count=10,
                       direction_spread="elongated_3d", packing="sparse", planarity="low")
    success_count = 0
    for i in range(20):
        shape = generate_shape_skeleton(spec)
        mirror = generate_mirror_reflection(shape["voxels"], (7, 7, 7))
        if mirror is not None:
             success_count += 1
    print(f"AsymmetricSkeleton (elongated_3d) generated {success_count}/20 chiral shapes")
    assert success_count > 10, "Elongated chiral should still produce many chiral shapes"
    print("AsymmetricSkeleton (elongated_3d) passed constraints.")

def test_bridge_skeleton():
    print("Testing LoopSkeleton...")
    spec = SkeletonSpec(archetype="bridge", voxel_count=12, num_loops=1,
                       direction_spread="moderate", packing="medium")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["cycle_count"] >= 1, f"Bridge missing cycle! {sfs['cycle_count']}"
        assert sfs["number_of_components"] == 1, f"Bridge disconnected!"
    print("LoopSkeleton passed constraints.")

def test_bridge_double_loop():
    """Bridge with two loops."""
    print("Testing LoopSkeleton (double loop)...")
    spec = SkeletonSpec(archetype="bridge", voxel_count=14, num_loops=2,
                       direction_spread="moderate", packing="medium")
    success_count = 0
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        if sfs["cycle_count"] >= 2:
            success_count += 1
        assert sfs["number_of_components"] == 1, f"Bridge disconnected!"
    print(f"LoopSkeleton (double) generated {success_count}/10 with 2+ cycles")
    assert success_count >= 5, "Double loop should reliably produce 2+ cycles"
    print("LoopSkeleton (double loop) passed constraints.")

def test_get_skeleton_spec():
    """Test that get_skeleton_spec maps cognitive levels correctly."""
    print("Testing get_skeleton_spec()...")

    # Low everything
    spec = get_skeleton_spec(
        {"spatial_form": "low", "structural_complexity": "low", "spatial_density": "low"},
        {"mental_rotation": "low", "mirror_discrimination": "low", "working_memory": "low"},
        target_voxel_count=8,
    )
    assert spec.archetype == "tree", f"Expected tree, got {spec.archetype}"
    assert spec.num_branches == 2, f"Expected 2 branches, got {spec.num_branches}"
    assert spec.packing == "sparse", f"Expected sparse, got {spec.packing}"
    assert spec.direction_spread == "planar", f"Expected planar, got {spec.direction_spread}"

    # High structural + high mirror → chiral
    spec = get_skeleton_spec(
        {"spatial_form": "high", "structural_complexity": "high", "spatial_density": "high"},
        {"mental_rotation": "high", "mirror_discrimination": "high", "working_memory": "high"},
        target_voxel_count=12,
    )
    assert spec.archetype == "chiral", f"Expected chiral, got {spec.archetype}"
    assert spec.num_branches == 5, f"Expected 5 branches, got {spec.num_branches}"
    assert spec.packing == "dense", f"Expected dense, got {spec.packing}"

    # High structural, no rotation/mirror → bridge
    spec = get_skeleton_spec(
        {"structural_complexity": "high"},
        {"mental_rotation": "low", "mirror_discrimination": "low"},
        target_voxel_count=10,
    )
    assert spec.archetype == "bridge", f"Expected bridge, got {spec.archetype}"
    assert spec.num_loops == 2, f"Expected 2 loops, got {spec.num_loops}"

    print("get_skeleton_spec() passed all assertions.")

def test_end_to_end():
    """Full pipeline: cognitive spec → skeleton spec → shape → features."""
    print("Testing end-to-end pipeline...")
    from cognitive_mapping import reverse_map_cognitive_profile
    from shape_features import ShapeFeatureSet

    shape_diffs = {"spatial_form": "medium", "structural_complexity": "medium", "spatial_density": "medium"}
    task_diffs = {"mental_rotation": "medium", "mirror_discrimination": "medium"}

    spec = get_skeleton_spec(shape_diffs, task_diffs, target_voxel_count=10)
    shape = generate_shape_skeleton(spec)

    # Verify features were computed
    feats = shape["features"]
    assert feats["voxel_count"] > 0, "No voxels generated"
    assert feats["number_of_components"] is not None, "Components not computed"

    # Reverse map to cognitive profile
    valid_keys = ShapeFeatureSet.model_fields.keys()
    sfs = ShapeFeatureSet(**{k: v for k, v in feats.items() if k in valid_keys and v is not None})
    profile = reverse_map_cognitive_profile(sfs, shape_diffs)
    print(f"  Fidelity: {profile.overall_fidelity:.2f}")
    for dim_name, dim_prof in profile.shape_dimensions.items():
        print(f"  {dim_name}: {dim_prof.level} (agreement: {dim_prof.agreement:.2f})")

    print("End-to-end pipeline passed.")


def test_expert_tree_skeleton():
    """Expert tree: 20 voxels, 7 branches, 10×10×10 grid."""
    print("Testing Expert TreeSkeleton...")
    spec = SkeletonSpec(archetype="tree", voxel_count=20, num_branches=7,
                       grid_size=(10, 10, 10),
                       direction_spread="elongated_3d", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Expert tree disconnected! {sfs['number_of_components']}"
        assert sfs["voxel_count"] == 20, f"Voxel count mismatch! {sfs['voxel_count']}"
        # Verify voxels fit within 10×10×10 bounds
        for v in shape["voxels"]:
            for coord in v:
                assert 0 <= coord < 10, f"Voxel {v} out of 10×10×10 bounds!"
    print("Expert TreeSkeleton passed constraints.")

def test_expert_bridge_multi_loop():
    """Expert bridge: 4 loops, 22 voxels, 10×10×10 grid."""
    print("Testing Expert LoopSkeleton (multi-loop)...")
    spec = SkeletonSpec(archetype="bridge", voxel_count=22, num_loops=4,
                       grid_size=(10, 10, 10),
                       direction_spread="moderate", packing="medium")
    success_count = 0
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Expert bridge disconnected!"
        if sfs["cycle_count"] >= 3:
            success_count += 1
        # Verify bounds
        for v in shape["voxels"]:
            for coord in v:
                assert 0 <= coord < 10, f"Voxel {v} out of 10×10×10 bounds!"
    print(f"Expert LoopSkeleton generated {success_count}/10 with 3+ cycles")
    assert success_count >= 5, "Expert multi-loop should reliably produce 3+ cycles"
    print("Expert LoopSkeleton (multi-loop) passed constraints.")

def test_expert_skeleton_spec():
    """Test that get_skeleton_spec maps expert levels correctly."""
    print("Testing get_skeleton_spec() for expert level...")

    # Expert structural, no rotation/mirror → bridge with expert params
    spec = get_skeleton_spec(
        {"spatial_form": "expert", "structural_complexity": "expert", "spatial_density": "expert"},
        {"mental_rotation": "low", "mirror_discrimination": "low"},
        target_voxel_count=20,
    )
    assert spec.archetype == "bridge", f"Expected bridge, got {spec.archetype}"
    assert spec.num_branches == 7, f"Expected 7 branches, got {spec.num_branches}"
    assert spec.num_loops == 4, f"Expected 4 loops, got {spec.num_loops}"
    assert spec.packing == "dense", f"Expected dense, got {spec.packing}"
    assert spec.grid_size == (10, 10, 10), f"Expected 10×10×10 grid, got {spec.grid_size}"
    assert spec.direction_spread == "elongated_3d", f"Expected elongated_3d, got {spec.direction_spread}"

    # Expert structural + expert mirror → chiral
    spec = get_skeleton_spec(
        {"structural_complexity": "expert"},
        {"mental_rotation": "expert", "mirror_discrimination": "expert"},
        target_voxel_count=18,
    )
    assert spec.archetype == "chiral", f"Expected chiral, got {spec.archetype}"
    assert spec.grid_size == (10, 10, 10), f"Expected 10×10×10 grid, got {spec.grid_size}"

    print("get_skeleton_spec() expert assertions passed.")

def test_expert_end_to_end():
    """Full expert pipeline: cognitive spec → skeleton spec → shape → features → reverse map."""
    print("Testing expert end-to-end pipeline...")
    from cognitive_mapping import reverse_map_cognitive_profile, get_difficulty_spec
    from shape_features import ShapeFeatureSet

    shape_diffs = {"spatial_form": "expert", "structural_complexity": "expert", "spatial_density": "expert"}
    task_diffs = {"mental_rotation": "low", "mirror_discrimination": "low"}

    # Test skeleton spec path
    spec = get_skeleton_spec(shape_diffs, task_diffs, target_voxel_count=25)
    assert spec.grid_size == (10, 10, 10), f"Expert grid should be 10×10×10"
    shape = generate_shape_skeleton(spec)
    feats = shape["features"]
    # Expert bridge with 4 loops needs ~23 voxels for the skeleton; allow ±3 tolerance
    assert 20 <= feats["voxel_count"] <= 28, f"Expert voxel count {feats['voxel_count']} outside 20-28 range"

    # Test difficulty spec path
    diff_spec = get_difficulty_spec(shape_diffs, task_diffs, target_voxel_count=25)
    assert diff_spec.shape_features.grid_size == (10, 10, 10), f"Expert grid should be 10×10×10"
    assert diff_spec.shape_features.voxel_count == 25

    # Reverse map to cognitive profile
    valid_keys = ShapeFeatureSet.model_fields.keys()
    sfs = ShapeFeatureSet(**{k: v for k, v in feats.items() if k in valid_keys and v is not None})
    profile = reverse_map_cognitive_profile(sfs, shape_diffs)
    print(f"  Expert fidelity: {profile.overall_fidelity:.2f}")
    for dim_name, dim_prof in profile.shape_dimensions.items():
        print(f"  {dim_name}: {dim_prof.level} (agreement: {dim_prof.agreement:.2f})")

    print("Expert end-to-end pipeline passed.")

def test_backward_compatibility():
    """Verify standard low/medium/high tiers are unchanged."""
    print("Testing backward compatibility...")
    from cognitive_mapping import get_difficulty_spec

    # Low difficulty should still produce 7×7×7 grid
    spec = get_difficulty_spec(
        {"spatial_form": "low", "structural_complexity": "low", "spatial_density": "low"},
        {"mental_rotation": "low"},
        target_voxel_count=8,
    )
    assert spec.shape_features.grid_size == (7, 7, 7), f"Low should use 7×7×7 grid"
    assert spec.shape_features.voxel_count == 8

    # High difficulty should still use 7×7×7 grid
    spec = get_difficulty_spec(
        {"spatial_form": "high", "structural_complexity": "high", "spatial_density": "high"},
        {"mental_rotation": "high"},
        target_voxel_count=12,
    )
    assert spec.shape_features.grid_size == (7, 7, 7), f"High should use 7×7×7 grid"

    # Standard skeleton spec
    gspec = get_skeleton_spec(
        {"structural_complexity": "high"},
        {"mental_rotation": "low"},
        target_voxel_count=12,
    )
    assert gspec.grid_size == (7, 7, 7), f"Standard skeleton should use 7×7×7 grid"
    assert gspec.num_branches == 5, f"High branches should be 5"

    print("Backward compatibility passed.")


# =============================================================================
# Extended skeleton tests
# =============================================================================

def test_lamina_skeleton():
    """Lamina: sheet/plate structures with high planarity."""
    print("Testing LaminaSkeleton...")
    spec = SkeletonSpec(archetype="lamina", voxel_count=12,
                       direction_spread="planar", packing="medium")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Lamina disconnected!"
        assert sfs["voxel_count"] == 12, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("LaminaSkeleton passed constraints.")

def test_lamina_thick():
    """Lamina with dense packing (thicker sheet)."""
    print("Testing LaminaSkeleton (dense/thick)...")
    spec = SkeletonSpec(archetype="lamina", voxel_count=15,
                       direction_spread="moderate", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Lamina disconnected!"
    print("LaminaSkeleton (dense/thick) passed constraints.")

def test_mesh_skeleton():
    """Mesh: regular lattice structures."""
    print("Testing MeshSkeleton...")
    spec = SkeletonSpec(archetype="mesh", voxel_count=12,
                       direction_spread="moderate", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Mesh disconnected!"
        assert sfs["voxel_count"] == 12, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("MeshSkeleton passed constraints.")

def test_mesh_planar():
    """Mesh in 2D lattice mode."""
    print("Testing MeshSkeleton (planar)...")
    spec = SkeletonSpec(archetype="mesh", voxel_count=10,
                       direction_spread="planar", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Mesh disconnected!"
    print("MeshSkeleton (planar) passed constraints.")

def test_spiral_skeleton():
    """Spiral: helical growth structures."""
    print("Testing SpiralSkeleton...")
    spec = SkeletonSpec(archetype="spiral", voxel_count=12,
                       direction_spread="elongated_3d", packing="medium")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Spiral disconnected!"
        assert sfs["voxel_count"] == 12, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("SpiralSkeleton passed constraints.")

def test_spiral_flat():
    """Spiral in flat/Archimedean mode."""
    print("Testing SpiralSkeleton (planar/flat)...")
    spec = SkeletonSpec(archetype="spiral", voxel_count=10,
                       direction_spread="planar", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Spiral disconnected!"
    print("SpiralSkeleton (planar/flat) passed constraints.")

def test_foam_skeleton():
    """Foam: packed cell-like structures."""
    print("Testing FoamSkeleton...")
    spec = SkeletonSpec(archetype="foam", voxel_count=12, num_branches=3,
                       direction_spread="moderate", packing="medium")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Foam disconnected!"
        assert sfs["voxel_count"] == 12, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("FoamSkeleton passed constraints.")

def test_foam_dense():
    """Foam with dense packing (thick walls)."""
    print("Testing FoamSkeleton (dense)...")
    spec = SkeletonSpec(archetype="foam", voxel_count=15, num_branches=4,
                       direction_spread="moderate", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Foam disconnected!"
    print("FoamSkeleton (dense) passed constraints.")

def test_bundle_skeleton():
    """Bundle: parallel fiber structures."""
    print("Testing BundleSkeleton...")
    spec = SkeletonSpec(archetype="bundle", voxel_count=12, num_branches=3,
                       direction_spread="elongated_3d", packing="dense")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Bundle disconnected!"
        assert sfs["voxel_count"] == 12, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("BundleSkeleton passed constraints.")

def test_bundle_sparse():
    """Bundle with wider fiber spacing."""
    print("Testing BundleSkeleton (sparse)...")
    spec = SkeletonSpec(archetype="bundle", voxel_count=14, num_branches=2,
                       direction_spread="moderate", packing="sparse")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Bundle disconnected!"
    print("BundleSkeleton (sparse) passed constraints.")

def test_fractal_skeleton():
    """Fractal: self-similar branching at multiple scales."""
    print("Testing FractalSkeleton...")
    spec = SkeletonSpec(archetype="fractal", voxel_count=15, num_branches=4,
                       direction_spread="moderate", packing="medium")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Fractal disconnected!"
        assert sfs["voxel_count"] == 15, f"Voxel count mismatch! {sfs['voxel_count']}"
    print("FractalSkeleton passed constraints.")

def test_fractal_sparse():
    """Fractal with long sub-branches."""
    print("Testing FractalSkeleton (sparse)...")
    spec = SkeletonSpec(archetype="fractal", voxel_count=12, num_branches=4,
                       direction_spread="elongated_3d", packing="sparse")
    for i in range(10):
        shape = generate_shape_skeleton(spec)
        sfs = shape["features"]
        assert sfs["number_of_components"] == 1, f"Fractal disconnected!"
    print("FractalSkeleton (sparse) passed constraints.")

def test_extended_skeleton_spec():
    """Test that archetype_hint in get_skeleton_spec selects extended skeletons."""
    print("Testing get_skeleton_spec() with archetype hints...")

    for archetype in ["lamina", "mesh", "spiral", "foam", "bundle", "fractal"]:
        spec = get_skeleton_spec(
            {"spatial_form": "medium", "structural_complexity": "medium",
             "spatial_density": "medium", "archetype_hint": archetype},
            {"mental_rotation": "low", "mirror_discrimination": "low"},
            target_voxel_count=12,
        )
        assert spec.archetype == archetype, f"Expected {archetype}, got {spec.archetype}"

    print("get_skeleton_spec() archetype hints passed.")

def test_extended_end_to_end():
    """Full pipeline for each extended skeleton."""
    print("Testing extended skeleton end-to-end pipeline...")
    from cognitive_mapping import reverse_map_cognitive_profile
    from shape_features import ShapeFeatureSet

    for archetype in ["lamina", "mesh", "spiral", "foam", "bundle", "fractal"]:
        shape_diffs = {
            "spatial_form": "medium", "structural_complexity": "medium",
            "spatial_density": "medium", "archetype_hint": archetype,
        }
        task_diffs = {"mental_rotation": "low", "mirror_discrimination": "low"}
        spec = get_skeleton_spec(shape_diffs, task_diffs, target_voxel_count=12)
        shape = generate_shape_skeleton(spec)
        feats = shape["features"]
        assert feats["voxel_count"] > 0, f"{archetype}: No voxels generated"
        assert feats["number_of_components"] == 1, f"{archetype}: Disconnected"
        assert shape["archetype"] == archetype, f"{archetype}: Wrong archetype in output"
        print(f"  {archetype}: OK (voxels={feats['voxel_count']}, "
              f"cycles={feats['cycle_count']}, bf={feats['branching_factor']:.1f})")

    print("Extended skeleton end-to-end pipeline passed.")


if __name__ == "__main__":
    test_tree_skeleton()
    test_tree_sparse_elongated()
    test_tree_dense_planar()
    test_chiral_skeleton()
    test_chiral_elongated()
    test_bridge_skeleton()
    test_bridge_double_loop()
    test_get_skeleton_spec()
    test_end_to_end()
    # Expert tier tests
    test_expert_tree_skeleton()
    test_expert_bridge_multi_loop()
    test_expert_skeleton_spec()
    test_expert_end_to_end()
    test_backward_compatibility()
    # Extended skeleton tests
    test_lamina_skeleton()
    test_lamina_thick()
    test_mesh_skeleton()
    test_mesh_planar()
    test_spiral_skeleton()
    test_spiral_flat()
    test_foam_skeleton()
    test_foam_dense()
    test_bundle_skeleton()
    test_bundle_sparse()
    test_fractal_skeleton()
    test_fractal_sparse()
    test_extended_skeleton_spec()
    test_extended_end_to_end()
    print("\nAll skeleton tests passed!")
